name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14.6 # Stable
      - run: |
          go get -v github.com/chips-project/gdrive
          file /home/runner/go/bin/gdrive
