name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.14.6 # Stable
    - name: Build
      run: |
        go get -v github.com/chips-project/gdrive
        file /home/runner/go/bin/gdrive
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: gdrive
        path: '/home/runner/go/bin/gdrive'
